### ISSUE TITLE
All fields in the screen are affected

### ISSUE THREAD

**Issue by rfvallina** [noomerzx/vue-barcode-scanner#14]
Hi, I have other input fields in the screen (even in separate components) and every time tab key is pressed on any of them the scanner gets executed.
Is not possible to init the scanner with a particular field/s?

**Comment by noomerzx** [comment]
Thx I'll implementing something that user can init a scanner event in optional ways.

May be if you have some Idea just create a pull request for that.

Thx a lot for great feedback I'm implementing this for inhouse project and now I'm switching to another and don't have time to improve this for long a go, So it's be good to have others help me improve thhis by the way :)
