### ISSUE TITLE
Listener not working on the electron wrapper

### ISSUE THREAD

**Issue by renzzynpass** [noomerzx/vue-barcode-scanner#19]
It perfectly works on the vue cli 3 production mode, but when I tried the vue electron module it works pretty well by running `yarn elecrtron:serve` but when I try to build it the electron production by running this. `yarn electron:build` the listener doesnt response and not trigger the data component.
Any ideas ?

**Comment by noomerzx** [comment]
never try it on electron before may be I'll take a look and give a suggestion

**Comment by zendiik** [comment]
When run `yarn electron:build`, it appears error: `Uncaught ReferenceError: barcodeIdentifier is not defined`. It might help.

**Comment by renztoygwapo** [comment]
> barcodeIdentifier

how to add that one?
I did not encounter that when I build the electron app.

Thanks

**Comment by renztoygwapo** [comment]
@noomerzx can you try it with electron app ?
Thanks

**Comment by zendiik** [comment]
I got the temporary solution. On npmjs.com is latest version 0.6.0 but on github is 0.7.0. In package.json just remove version and add this url `git+https://github.com/noomerzx/vue-barcode-scanner.git`. It works fine after install. Author could upload a new version to the npmjs.com :)

**Comment by renztoygwapo** [comment]
@zendiik May I see your package.json looks like ?
also @noomerzx can you upload the latest version 0.7.0 in the npm.js to solve the issue please?

Great Thanks.

**Comment by renztoygwapo** [comment]
It looks like it works well @zendiik 
Great Thanks

**Comment by noomerzx** [comment]
@renztoygwapo 
Sorry for late reply and Thx to @zendiik  for the solution. I've do this for support browser mainly. So I'm not tested on another platform yet, But Thx for feedback and I'll take a look to support more platform in the future.
