### ISSUE TITLE
Why barcode scanner opens Chrome developer console in chrome?

### ISSUE THREAD

**Issue by phanchanra** [noomerzx/vue-barcode-scanner#21]
I just bought a barcode reader from China model Honeywell HH400. It works perfectly when I use it other device. But now I use it in my web application and I am getting a problem. It always toggle Chrome developer console. I also tried scanning barcode into URL bar, and it does the same. Does it have an event to trigger F12 what? Or misconfiguration with the scanner that I don't know?

**Comment by noomerzx** [comment]
You use it individually or with this plugin ? May be the scanner trigger F12 as a last key as you said ,So maybe you need to handle that F12 by yourself on web app.

**Comment by phanchanra** [comment]
I use this plugin. Can you show me some explanation?

**Comment by noomerzx** [comment]
For now this plugin don't accepts F12 as a last key captured. ("only know TAB and ENTER as a last key capture then it will stop scanning more."), May be need some update or you can create PR for the features like "configuration last key capture" to config last key capture to let plugin stop scanning more.

**Comment by phanchanra** [comment]
Thank you
